
smart_module.user.index:
    path: /
    defaults:
        _controller: UserModuleBundle:User:index

smart_module.user.edit:
    path: /edit
    defaults:
        _controller: UserModuleBundle:User:edit

#smart_module.user.login:
#    path: /login
#    defaults:
#        _controller: FOSUserBundle:Security:login

smart_module.user.change-password:
    path: /change-password
    defaults:
        _controller: UserModuleBundle:User:changePassword

# Resetting password
smart_module.user.resetting:
    path: /resetting/
    defaults:
        _controller: UserModuleBundle:User:resettingRequest

smart_module.user.resetting.send-email:
    path: /resetting/send-email
    defaults:
        _controller: FOSUserBundle:Resetting:sendEmail

smart_module.user.resetting.check-email:
    path: /resetting/check-email
    defaults:
        _controller: FOSUserBundle:Resetting:checkEmail

smart_module.user.resetting.reset:
    path: /resetting/reset/{token}
    defaults:
        _controller: FOSUserBundle:Resetting:reset

# Registration
smart_module.user.registration:
    path: /register/
    defaults:
        _controller: UserModuleBundle:User:register

smart_module.user.registration.check-email:
    path: /register/check-email
    defaults:
        _controller: UserModuleBundle:User:registerCheckEmail

smart_module.user.registration.confirm:
    path: /register/confirm/{token}
    defaults:
        _controller: FOSUserBundle:Registration:confirm

smart_module.user.registration.confirmed:
    path: /register/confirmed
    defaults:
        _controller: FOSUserBundle:Registration:confirmed
